import { describe, it, expect } from 'vitest'

// Test that ALL hooks are re-exported correctly from the split files
describe('hooks exports', () => {
  it('exports all CRM hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useCrmPipeline).toBeDefined()
    expect(hooks.useCrmStages).toBeDefined()
    expect(hooks.useCrmDeals).toBeDefined()
    expect(hooks.useCrmDeal).toBeDefined()
    expect(hooks.useCrmWonDeals).toBeDefined()
    expect(hooks.useCrmPendingOrders).toBeDefined()
    expect(hooks.useCrmContacts).toBeDefined()
    expect(hooks.useCreateCrmDeal).toBeDefined()
    expect(hooks.useCreateCrmContact).toBeDefined()
    expect(hooks.useUpdateCrmContact).toBeDefined()
    expect(hooks.useDeleteCrmContact).toBeDefined()
    expect(hooks.useRegisterOrder).toBeDefined()
    expect(hooks.useConfirmOrder).toBeDefined()
    expect(hooks.useCrmAnalytics).toBeDefined()
    expect(hooks.useUpdateCrmDeal).toBeDefined()
    expect(hooks.useCrmActivities).toBeDefined()
    expect(hooks.useCreateCrmActivity).toBeDefined()
    expect(hooks.useUpdateCrmActivity).toBeDefined()
    expect(hooks.useCrmCompanies).toBeDefined()
    expect(hooks.useCreateCrmCompany).toBeDefined()
    expect(hooks.useCrmCompany).toBeDefined()
  })

  it('exports all Portal hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.usePortalStatus).toBeDefined()
    expect(hooks.usePortalCustomers).toBeDefined()
    expect(hooks.usePortalPersons).toBeDefined()
    expect(hooks.usePortalProjectTypes).toBeDefined()
    expect(hooks.usePortalLocations).toBeDefined()
    expect(hooks.usePortalAccountManagers).toBeDefined()
    expect(hooks.useMyPortalAccountManager).toBeDefined()
    expect(hooks.usePortalProtocolByCustomer).toBeDefined()
    expect(hooks.useCreatePortalOffer).toBeDefined()
    expect(hooks.usePortalOfferProtocol).toBeDefined()
    expect(hooks.useCreatePortalActivity).toBeDefined()
    expect(hooks.useAssignPortalEmployee).toBeDefined()
    expect(hooks.useDealProject).toBeDefined()
    expect(hooks.useDealProgress).toBeDefined()
    expect(hooks.useApproveOffer).toBeDefined()
    expect(hooks.usePortalActivityTypes).toBeDefined()
    expect(hooks.useCreatePortalActivityOnProject).toBeDefined()
    expect(hooks.useAssignEmployeeToActivity).toBeDefined()
    expect(hooks.usePortalOffer).toBeDefined()
    expect(hooks.usePortalOffers).toBeDefined()
    expect(hooks.useMatchCustomer).toBeDefined()
    expect(hooks.useBatchMatchCustomers).toBeDefined()
    expect(hooks.useLinkDealToProject).toBeDefined()
  })

  it('exports all deal resource hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useDealResources).toBeDefined()
    expect(hooks.useAddDealResource).toBeDefined()
    expect(hooks.useUpdateDealResource).toBeDefined()
    expect(hooks.useRemoveDealResource).toBeDefined()
    expect(hooks.useDealRequiresResources).toBeDefined()
    expect(hooks.useCreateOfferFromDeal).toBeDefined()
    expect(hooks.useCreateProjectFromDeal).toBeDefined()
  })

  it('exports all pipeline hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.usePipelineTemplates).toBeDefined()
    expect(hooks.useCreatePipelineTemplate).toBeDefined()
    expect(hooks.useUpdatePipelineTemplate).toBeDefined()
    expect(hooks.useDeletePipelineTemplate).toBeDefined()
    expect(hooks.useAddTemplateStage).toBeDefined()
    expect(hooks.useUpdateTemplateStage).toBeDefined()
    expect(hooks.useDeleteTemplateStage).toBeDefined()
  })

  it('exports all auth hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useProfile).toBeDefined()
    expect(hooks.useUpdateProfile).toBeDefined()
    expect(hooks.useMyPermissions).toBeDefined()
    expect(hooks.useTeamUsers).toBeDefined()
    expect(hooks.useInviteUser).toBeDefined()
    expect(hooks.useUpdateUserRole).toBeDefined()
    expect(hooks.useUpdateUserCrmRole).toBeDefined()
    expect(hooks.useToggleUserActive).toBeDefined()
  })

  it('exports all document hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useDealDocuments).toBeDefined()
    expect(hooks.useAddDealDocument).toBeDefined()
    expect(hooks.useDeleteDealDocument).toBeDefined()
    expect(hooks.useUploadDealDocument).toBeDefined()
  })

  it('exports all email hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useEmailTemplates).toBeDefined()
    expect(hooks.useEmailTemplate).toBeDefined()
    expect(hooks.useCreateEmailTemplate).toBeDefined()
    expect(hooks.useUpdateEmailTemplate).toBeDefined()
    expect(hooks.usePreviewTemplate).toBeDefined()
    expect(hooks.useEmailSends).toBeDefined()
    expect(hooks.useSendEmail).toBeDefined()
    expect(hooks.useEmailAnalytics).toBeDefined()
    expect(hooks.useEmailSequences).toBeDefined()
    expect(hooks.useCreateSequence).toBeDefined()
    expect(hooks.useGenerateEmail).toBeDefined()
    expect(hooks.useRefineEmail).toBeDefined()
    expect(hooks.useSendMessage).toBeDefined()
  })

  it('exports all product/social hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useProducts).toBeDefined()
    expect(hooks.useCreateProduct).toBeDefined()
    expect(hooks.useUpdateProduct).toBeDefined()
    expect(hooks.useRoles).toBeDefined()
    expect(hooks.useCreateRole).toBeDefined()
    expect(hooks.useDeleteRole).toBeDefined()
    expect(hooks.useOrigins).toBeDefined()
    expect(hooks.useCreateOrigin).toBeDefined()
    expect(hooks.useUpdateOrigin).toBeDefined()
    expect(hooks.useDeleteOrigin).toBeDefined()
    expect(hooks.useActivityTypes).toBeDefined()
    expect(hooks.useCreateActivityType).toBeDefined()
    expect(hooks.useUpdateActivityType).toBeDefined()
    expect(hooks.useSocialPipelineStages).toBeDefined()
    expect(hooks.useDealProducts).toBeDefined()
    expect(hooks.useAddDealProduct).toBeDefined()
    expect(hooks.useRemoveDealProduct).toBeDefined()
    expect(hooks.useAuditLog).toBeDefined()
    expect(hooks.useScorecard).toBeDefined()
    expect(hooks.useCompensationRules).toBeDefined()
    expect(hooks.useCreateCompensationRule).toBeDefined()
    expect(hooks.useMonthlyCompensation).toBeDefined()
    expect(hooks.useCalculateCompensation).toBeDefined()
    expect(hooks.useConfirmCompensation).toBeDefined()
    expect(hooks.useMarkPaidCompensation).toBeDefined()
    expect(hooks.useSocialDashboards).toBeDefined()
  })

  it('exports resource hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useResources).toBeDefined()
    expect(hooks.useCreateResource).toBeDefined()
    expect(hooks.useUpdateResource).toBeDefined()
    expect(hooks.useAddResourceSkill).toBeDefined()
    expect(hooks.useResourceMatch).toBeDefined()
    expect(hooks.useResourceBench).toBeDefined()
  })

  it('exports other/accounting hooks', async () => {
    const hooks = await import('../../hooks')
    expect(hooks.useCrmStats).toBeDefined()
    expect(hooks.useDashboard).toBeDefined()
    expect(hooks.useYearlyStats).toBeDefined()
    expect(hooks.useInvoices).toBeDefined()
    expect(hooks.usePianoConti).toBeDefined()
    expect(hooks.useBalanceSheet).toBeDefined()
    expect(hooks.useBankAccounts).toBeDefined()
    expect(hooks.useCashflow).toBeDefined()
    expect(hooks.useExpenses).toBeDefined()
    expect(hooks.useAssets).toBeDefined()
    expect(hooks.useF24s).toBeDefined()
    expect(hooks.useCeoDashboard).toBeDefined()
    expect(hooks.useConversations).toBeDefined()
    expect(hooks.useScadenzarioAttivo).toBeDefined()
    expect(hooks.useScadenzarioPassivo).toBeDefined()
    expect(hooks.useFidi).toBeDefined()
    expect(hooks.useEleviaUseCases).toBeDefined()
  })
})
