/**
 * AITodoPanel — "Mission Control" side drawer for AI-generated daily tasks.
 *
 * Sprint 48: Collapsible right-side panel showing actionable todo items
 * generated by the Sales Agent during pipeline auto-analysis.
 * Each item links to a deal and shows priority, action text, and quick buttons.
 */

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  ChevronRight,
  ChevronLeft,
  Check,
  ArrowRight,
  Phone,
  Pencil,
  Calendar,
  Trash2,
  ClipboardList,
} from 'lucide-react'
import type { AITodoItem } from '../../context/UIHighlightContext'

interface AITodoPanelProps {
  items: AITodoItem[]
  onComplete: (id: string) => void
  onNavigate: (dealId: string) => void
  onDismiss: (id: string) => void
  onClose: () => void
  isOpen: boolean
}

const ICON_MAP: Record<string, typeof Check> = {
  check: Check,
  phone: Phone,
  edit: Pencil,
  calendar: Calendar,
  trash: Trash2,
}

const PRIORITY_CONFIG = {
  high: {
    border: 'border-l-red-500',
    iconBg: 'bg-red-50',
    iconText: 'text-red-600',
    dot: 'bg-red-500',
  },
  medium: {
    border: 'border-l-amber-500',
    iconBg: 'bg-amber-50',
    iconText: 'text-amber-600',
    dot: 'bg-amber-500',
  },
  low: {
    border: 'border-l-emerald-500',
    iconBg: 'bg-emerald-50',
    iconText: 'text-emerald-600',
    dot: 'bg-emerald-500',
  },
} as const

const panelVariants = {
  open: { width: 280, opacity: 1 },
  closed: { width: 36, opacity: 1 },
}

const cardVariants = {
  hidden: { opacity: 0, x: 40 },
  visible: (i: number) => ({
    opacity: 1,
    x: 0,
    transition: { delay: i * 0.05, duration: 0.25, ease: 'easeOut' },
  }),
  exit: { opacity: 0, x: 40, transition: { duration: 0.15 } },
}

export default function AITodoPanel({
  items,
  onComplete,
  onNavigate,
  onDismiss,
  onClose,
  isOpen,
}: AITodoPanelProps) {
  const [collapsed, setCollapsed] = useState(false)

  // Sort: incomplete first, then by priority, completed at bottom
  const priorityOrder = { high: 0, medium: 1, low: 2 }
  const sorted = [...items].sort((a, b) => {
    if (a.completed !== b.completed) return a.completed ? 1 : -1
    return priorityOrder[a.priority] - priorityOrder[b.priority]
  })

  const incompleteCount = items.filter((i) => !i.completed).length

  if (!isOpen) return null

  return (
    <motion.div
      className="flex-none border-l border-gray-200 bg-gray-50/80 overflow-hidden"
      variants={panelVariants}
      initial="closed"
      animate={collapsed ? 'closed' : 'open'}
      transition={{ type: 'spring', damping: 24, stiffness: 300 }}
    >
      {/* Collapsed bar */}
      {collapsed ? (
        <div className="flex h-full flex-col items-center pt-3">
          <button
            onClick={() => setCollapsed(false)}
            className="rounded-md p-1 text-gray-400 hover:bg-gray-200 hover:text-gray-600 transition-colors"
            aria-label="Espandi pannello azioni"
          >
            <ChevronLeft className="h-4 w-4" />
          </button>
          {incompleteCount > 0 && (
            <span className="mt-2 flex h-5 w-5 items-center justify-center rounded-full bg-blue-600 text-[10px] font-bold text-white">
              {incompleteCount}
            </span>
          )}
        </div>
      ) : (
        <div className="flex h-full flex-col">
          {/* Header */}
          <div className="flex items-center justify-between bg-slate-900 px-3 py-2.5">
            <div className="flex items-center gap-2">
              <ClipboardList className="h-4 w-4 text-slate-300" />
              <span className="text-sm font-semibold text-white">Oggi</span>
              {incompleteCount > 0 && (
                <span className="flex h-5 min-w-[20px] items-center justify-center rounded-full bg-blue-500 px-1.5 text-[10px] font-bold text-white">
                  {incompleteCount}
                </span>
              )}
            </div>
            <div className="flex items-center gap-1">
              <button
                onClick={() => setCollapsed(true)}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200 transition-colors"
                aria-label="Comprimi pannello"
              >
                <ChevronRight className="h-3.5 w-3.5" />
              </button>
              <button
                onClick={onClose}
                className="rounded p-1 text-slate-400 hover:bg-slate-800 hover:text-slate-200 transition-colors"
                aria-label="Chiudi pannello azioni"
              >
                <span className="text-xs">&times;</span>
              </button>
            </div>
          </div>

          {/* Todo list */}
          <div className="flex-1 overflow-y-auto px-2 py-2 space-y-1.5">
            <AnimatePresence mode="popLayout">
              {sorted.map((item, index) => {
                const pStyle = PRIORITY_CONFIG[item.priority]
                const IconComp = ICON_MAP[item.icon] || Check

                return (
                  <motion.div
                    key={item.id}
                    custom={index}
                    variants={cardVariants}
                    initial="hidden"
                    animate="visible"
                    exit="exit"
                    layout
                    className={`relative rounded-lg border border-gray-200 border-l-4 ${pStyle.border} bg-white shadow-sm transition-all ${
                      item.completed ? 'opacity-50 grayscale' : ''
                    }`}
                  >
                    <div className="p-2">
                      {/* Icon + Client name */}
                      <div className="flex items-start gap-2">
                        <div
                          className={`mt-0.5 flex h-5 w-5 flex-none items-center justify-center rounded ${pStyle.iconBg}`}
                        >
                          <IconComp className={`h-3 w-3 ${pStyle.iconText}`} />
                        </div>
                        <div className="min-w-0 flex-1">
                          <p
                            className={`text-xs font-semibold text-gray-800 truncate ${
                              item.completed ? 'line-through' : ''
                            }`}
                          >
                            {item.clientName}
                          </p>
                          <p
                            className={`mt-0.5 text-[11px] leading-snug text-gray-500 line-clamp-2 ${
                              item.completed ? 'line-through' : ''
                            }`}
                          >
                            {item.action}
                          </p>
                          {item.stage && (
                            <span className="mt-1 inline-block rounded bg-gray-100 px-1.5 py-0.5 text-[9px] font-medium text-gray-500">
                              {item.stage}
                            </span>
                          )}
                        </div>
                        {/* Dismiss button */}
                        <button
                          onClick={() => onDismiss(item.id)}
                          className="flex-none rounded p-0.5 text-gray-300 hover:bg-gray-100 hover:text-gray-500 transition-colors"
                          aria-label={`Rimuovi azione per ${item.clientName}`}
                        >
                          <span className="text-[10px]">&times;</span>
                        </button>
                      </div>

                      {/* Action buttons */}
                      {!item.completed && (
                        <div className="mt-2 flex items-center gap-1.5">
                          <button
                            onClick={() => onComplete(item.id)}
                            className="inline-flex items-center gap-1 rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-medium text-emerald-700 hover:bg-emerald-100 transition-colors"
                          >
                            <Check className="h-3 w-3" />
                            Fatto
                          </button>
                          <button
                            onClick={() => onNavigate(item.dealId)}
                            className="inline-flex items-center gap-1 rounded-md bg-blue-50 px-2 py-1 text-[10px] font-medium text-blue-700 hover:bg-blue-100 transition-colors"
                          >
                            <ArrowRight className="h-3 w-3" />
                            Vai
                          </button>
                        </div>
                      )}

                      {/* Completed indicator */}
                      {item.completed && (
                        <div className="mt-1.5 flex items-center gap-1 text-[10px] text-emerald-600">
                          <Check className="h-3 w-3" />
                          <span>Completato</span>
                        </div>
                      )}
                    </div>
                  </motion.div>
                )
              })}
            </AnimatePresence>

            {items.length === 0 && (
              <div className="flex flex-col items-center justify-center py-8 text-center">
                <ClipboardList className="h-8 w-8 text-gray-300" />
                <p className="mt-2 text-xs text-gray-400">
                  Nessuna azione per oggi
                </p>
                <p className="mt-1 text-[10px] text-gray-300">
                  Chiedi al chatbot di analizzare la pipeline
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </motion.div>
  )
}
