"""Default agent configurations (US-A03)."""

DEFAULT_AGENTS = [
    {
        "agent_type": "fisco",
        "display_name": "Agente Fisco",
        "icon": "\U0001f4cb",
        "visible": True,
        "enabled": True,
        "personality": "Esperto fiscale italiano, preciso e aggiornato sulle normative.",
    },
    {
        "agent_type": "conta",
        "display_name": "Agente Contabilita",
        "icon": "\U0001f4d2",
        "visible": True,
        "enabled": True,
        "personality": "Contabile esperto in partita doppia e registrazioni contabili.",
    },
    {
        "agent_type": "cashflow",
        "display_name": "Agente Cash Flow",
        "icon": "\U0001f4b0",
        "visible": True,
        "enabled": True,
        "personality": "Analista finanziario specializzato in previsioni di cassa.",
    },
    {
        "agent_type": "conto_economico",
        "display_name": "Agente Setup",
        "icon": "\U0001f3d7\ufe0f",
        "visible": True,
        "enabled": True,
        "personality": "Assistente per la configurazione iniziale dell'azienda.",
    },
    {
        "agent_type": "normativo",
        "display_name": "Agente Normativo",
        "icon": "\u2696\ufe0f",
        "visible": True,
        "enabled": True,
        "personality": "Esperto di normative e adempimenti per PMI italiane.",
    },
    {
        "agent_type": "parser",
        "display_name": "Parser",
        "icon": "\U0001f4c4",
        "visible": False,
        "enabled": True,
        "personality": None,
    },
    {
        "agent_type": "learning",
        "display_name": "Learning",
        "icon": "\U0001f9e0",
        "visible": False,
        "enabled": True,
        "personality": None,
    },
    {
        "agent_type": "ocr",
        "display_name": "OCR",
        "icon": "\U0001f4f7",
        "visible": False,
        "enabled": True,
        "personality": None,
    },
    {
        "agent_type": "orchestrator",
        "display_name": "AgentFlow",
        "icon": "\U0001f916",
        "visible": False,
        "enabled": True,
        "personality": "Orchestratore principale del sistema AgentFlow.",
    },
]
