"""Default dashboard widget definitions."""

DEFAULT_WIDGETS: list[dict] = [
    {
        "id": "w1",
        "type": "stat_card",
        "title": "Ricavi Totali",
        "data_source": "yearly_stats",
        "data_path": "ricavi_totali",
        "config": {
            "format": "currency",
            "color": "green",
            "subtitle_path": "fatture_attive.count",
            "subtitle_suffix": " fatture + corrispettivi",
        },
        "layout": {"x": 0, "y": 0, "w": 4, "h": 2},
    },
    {
        "id": "w2",
        "type": "stat_card",
        "title": "Costi Totali",
        "data_source": "yearly_stats",
        "data_path": "costi_totali",
        "config": {
            "format": "currency",
            "color": "orange",
            "subtitle": "fornitori + personale + spese",
        },
        "layout": {"x": 4, "y": 0, "w": 4, "h": 2},
    },
    {
        "id": "w3",
        "type": "stat_card",
        "title": "Margine (EBITDA)",
        "data_source": "yearly_stats",
        "data_path": "margine_lordo",
        "config": {
            "format": "currency",
            "color": "blue",
        },
        "layout": {"x": 8, "y": 0, "w": 4, "h": 2},
    },
    {
        "id": "w_pers",
        "type": "stat_card",
        "title": "Costo Personale",
        "data_source": "yearly_stats",
        "data_path": "costo_personale.totale",
        "config": {
            "format": "currency",
            "color": "purple",
            "subtitle_path": "costo_personale.count",
            "subtitle_suffix": " cedolini",
        },
        "layout": {"x": 0, "y": 2, "w": 3, "h": 2},
    },
    {
        "id": "w_forn",
        "type": "stat_card",
        "title": "Fornitori",
        "data_source": "yearly_stats",
        "data_path": "fatture_passive.totale",
        "config": {
            "format": "currency",
            "color": "orange",
            "subtitle_path": "fatture_passive.count",
            "subtitle_suffix": " fatture",
        },
        "layout": {"x": 3, "y": 2, "w": 3, "h": 2},
    },
    {
        "id": "w_spese",
        "type": "stat_card",
        "title": "Note Spese",
        "data_source": "yearly_stats",
        "data_path": "note_spese.totale",
        "config": {
            "format": "currency",
            "color": "gray",
            "subtitle_path": "note_spese.count",
            "subtitle_suffix": " voci",
        },
        "layout": {"x": 6, "y": 2, "w": 3, "h": 2},
    },
    {
        "id": "w_fin",
        "type": "stat_card",
        "title": "Finanziamenti",
        "data_source": "yearly_stats",
        "data_path": "finanziamenti.totale_annuo",
        "config": {
            "format": "currency",
            "color": "red",
            "subtitle_path": "finanziamenti.count",
            "subtitle_suffix": " prestiti",
        },
        "layout": {"x": 9, "y": 2, "w": 3, "h": 2},
    },
    {
        "id": "w5",
        "type": "bar_chart",
        "title": "Fatturato Mensile",
        "data_source": "yearly_stats",
        "data_path": "fatture_per_mese",
        "config": {
            "x_key": "mese",
            "y_keys": [
                {"key": "attive_totale", "color": "#22c55e", "name": "Emesse"},
                {"key": "passive_totale", "color": "#f97316", "name": "Ricevute"},
            ],
        },
        "layout": {"x": 0, "y": 4, "w": 12, "h": 4},
    },
    {
        "id": "w6",
        "type": "table",
        "title": "Top 10 Clienti",
        "data_source": "yearly_stats",
        "data_path": "top_clienti",
        "config": {
            "columns": [
                {"key": "nome", "label": "Cliente"},
                {"key": "count", "label": "Fatt."},
                {"key": "totale", "label": "Totale", "format": "currency"},
            ],
        },
        "layout": {"x": 0, "y": 8, "w": 6, "h": 4},
    },
    {
        "id": "w7",
        "type": "table",
        "title": "Top 10 Fornitori",
        "data_source": "yearly_stats",
        "data_path": "top_fornitori",
        "config": {
            "columns": [
                {"key": "nome", "label": "Fornitore"},
                {"key": "count", "label": "Fatt."},
                {"key": "totale", "label": "Totale", "format": "currency"},
            ],
        },
        "layout": {"x": 6, "y": 8, "w": 6, "h": 4},
    },
]
